DROP DATABASE IF EXISTS TWITTERTEST;
CREATE DATABASE TWITTERTEST;

USE TWITTERTEST;

DROP USER IF EXISTS test@'localhost';
CREATE USER test@'localhost' IDENTIFIED WITH mysql_native_password BY 'dawson' REQUIRE NONE;
GRANT ALL ON TWITTERTEST.* TO test@'localhost';

FLUSH PRIVILEGES;

